config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'static_pages#home'
  get 'home', to: 'static_pages#home', as: 'home'

  match "/stories/search" => "stories#search", via: :get
  get 'stories/:id/view', to: 'stories#view', as: 'view_story'
  get 'stories/awaiting_approval', to: 'stories#awaiting_approval', as: 'view_awaiting_approval'
  resources :stories
  #get 'stories/new', to:'stories#new', as: 'stories'

end

app/models/story.rb
class Story < ActiveRecord::Base
	validates :name, presence: true
	validates :title, presence: true
	validates :content, presence: true
	
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		
	end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	before_filter :authenticate_user!, :only => [:edit, :new, :create, :update, :destroy, :awaiting_approval]
	def index
		@stories = Story.where(status: "Approved").all.order("name ASC")
	end

	def search 
		k = params[:keyword].downcase
		if k == "empty"
			@stories = Story.where(status: "Approved").all.order("name ASC")
		else
			@stories = []
			Story.where(status: "Approved").all.each do |s|
				if  s.name != nil and s.name.downcase.include? k
						@stories << s
				end
			end
		end
		respond_to do |format|
			format.html {redirect_to stories_url}
			format.js {}
		end
	end

	def view
		@story = Story.find(params[:id])
	end

	def edit
		@story = Story.find(params[:id])
	end

	def new
		@story = Story.new
	end

	def create 
		user = User.find(current_user)
		s = user.stories.create(params.require(:story).permit(:name, :title, :content)) do |x|
			x.status = "Awaiting Approval"
		end		
		if s.valid?
			flash[:notice] = "Successfully Created Testimony. Awaiting Approval."
			render :js => "window.location = '/stories'"
		else
			flash[:error] = "Error Creating Testimony. Please Fill Out All Fields."
			render "layouts/fail"
		end
	end

	def update

		@story = Story.find(params[:id])
		if current_user.level == "Admin"
			@story.update(params.require(:story).permit(:name, :title, :content, :status))
		else
			@story.update(params.require(:story).permit(:name, :title, :content))
		end

		if @story.valid?
			flash[:notice] = "Successfully Updated Testimony."
			render "layouts/success"
		else
			flash[:error] = "Error Updating Testimony! Make Sure No Field Is Blank!"
			render "layouts/fail"
		end
	end

	def destroy
		@story = Story.find(params[:id])
	  	@story.destroy
	  	redirect_to stories_path	
	end

	def awaiting_approval
		if current_user.level == "Admin"
			@stories = Story.where(status: "Awaiting Approval")
		else
			redirect_to stories_path
		end
		#render "index"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |type, message| %>
  	<% if type == "error" %>
  		<div class="alert alert-danger" role="alert"><%= type %>: <%= message %></div>
  	<% else %>
  		<div class="alert alert-success" role="alert"><%= type %>: <%= message %></div>
    <% end %>
    
  <% end %>
</div>
<% flash.clear %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testimony</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid">
	  
	  <div class="row"><br><br><br><br>
	    <div class="col-sm-2 col-sm-offset-10 col-md-3 col-md-offset-7">
	    	<nav class="navbar navbar-transparent">
	    		<div class="nav_links">
					<ul class="nav navbar-nav"> 
					        <li><%= link_to "Home", home_path() %></li>
					        <li><%= link_to "Testimonies", stories_path() %></li>
					        <li><%= link_to "Create Your Testimony", new_story_path() %></li>
					        <% if user_signed_in? and current_user.level == "Admin" %>
					        	<li><%= link_to "Need Approval", view_awaiting_approval_path() %></li>	
					        <% end %>
					        <% if user_signed_in? %>
					        	<li><%= link_to "Log Out", destroy_user_session_path(), method: :delete %></li>
					        <% else %>
					        	 <li><%= link_to "Log In", new_user_session_path() %></li>
					        <% end %> 
					</ul>
					
				</div>
	    	</nav>
	    </div>
	  </div>
	</div>

<%= render "layouts/flash_messages.html.erb" %>
<%= yield %>
</body>
</html>

app/views/layouts/fail.js.erb
$("#flash_messages").html('<%= escape_javascript(render "layouts/flash_messages") %>');
$("#action").prop('disabled', false);
alert("Error Updating!");

app/views/layouts/success.js.erb
$("#flash_messages").html('<%= escape_javascript(render "layouts/flash_messages") %>');
if(document.getElementById("action") != null){
	$("#action").prop('disabled', false);
}

app/views/static_pages/home.html.erb
<center>
<div id="welcome">
	Tell Your story!
</div>
</center>

app/views/stories/_story.html.erb
<tr>
	<td><%= story.name %></td>
	<td><%= story.title %></td>
	<td><%= link_to "", view_story_path(story), class: "glyphicon glyphicon-eye-open" %></td>
	<% if user_signed_in? and (story.user == current_user or current_user.level == "Admin") %>
		<td><%= link_to "", edit_story_path(story), class: "glyphicon glyphicon-pencil" %></td>
		<td><%= link_to "", story_path(story), data:{confirm: 'Are you sure?'},  class: "glyphicon glyphicon-trash", method: :delete %></td>
	<% end %>

</tr>

app/views/stories/awaiting_approval.html.erb
<br><br>
<div class="col-sm-2 col-sm-offset-10 col-md-6 col-md-offset-3">
	<div class="create_test">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-2">
					<center><h1>Testimony Index</h1></center>
					<br>
						<table id="stories-table" class="table table-hover">
							<thead>
								<th>Name</th> 
								<th>Title</th>  
								<th>View</th> 
								<th></th>
								<th></th> 
							</thead>	
							<tbody>
								<%= render @stories %>
							</tbody>
							
						</table>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/stories/edit.html.erb
<br><br>
<div class="col-sm-2 col-sm-offset-10 col-md-6 col-md-offset-3">
	<div class="create_test">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-2">
					<h1>Edit Testimony</h1>
						<%= form_for(@story, :remote => true, class: 'form-horizontal', :html => { :id => "form_correct" }) do |f| %>
							<fieldset>
								<div class = "form-group">
									<%= f.label :name %>
									<%= f.text_field :name, class: "form-control"  %>
								</div>
							
								<div class = "form-group">
									<%= f.label :title %>
									<%= f.text_field :title, class: "form-control"  %>
								</div>
							
								<div class = "form-group">
									<%= f.label :content %>
									<%= f.text_area :content, size: "30x10", class: "form-control"  %>
								</div>
								<% if user_signed_in? and current_user.level == "Admin" %>
									<div class = "form-group">
										<%= f.label :status %>
										<%= f.select :status, ['Awaiting Approval', 'Approved'], class: "form-control"%>
									</div>
								<% end %>

								<div class = "form-group">
									<%= f.submit(class: "btn btn-primary btn-sm", :id => "action") %>
								</div>
							</fieldset>
						<% end %> 
				</div>
			</div>
		</div>
	</div>
</div>




app/views/stories/index.html.erb
<br><br>
<div class="col-sm-2 col-sm-offset-10 col-md-6 col-md-offset-3">
	<div class="create_test">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-2">
					<center><h1>Testimony Index</h1></center>
					<br>
						<input id="search" type="text" name="Search" placeholder="Name Search"><br>
						<table id="stories-table" class="table table-hover">
							<thead>
								<th>Name</th> 
								<th>Title</th>  
								<th>View</th> 
								<th></th>
								<th></th> 
							</thead>	
							<tbody>
								<%= render @stories %>
							</tbody>
							
						</table>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/stories/new.html.erb
<br><br>
<div class="col-sm-2 col-sm-offset-10 col-md-6 col-md-offset-3">
	<div class="create_test">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-2">
					<h1>Create Testimony</h1>
						<%= form_for(@story, :remote => true, class: 'form-horizontal', :html => { :id => "form_correct" }) do |f| %>
							<fieldset>
								<div class = "form-group">
									<%= f.label :name %>
									<%= f.text_field :name, class: "form-control"  %>
								</div>
							
								<div class = "form-group">
									<%= f.label :title %>
									<%= f.text_field :title, class: "form-control"  %>
								</div>
							
								<div class = "form-group">
									<%= f.label :content %>
									<%= f.text_area :content, size: "30x10", class: "form-control"  %>
								</div>
							
								<div class = "form-group">
									<%= f.submit(class: "btn btn-primary btn-sm", :id => "action") %>
								</div>
							</fieldset>
						<% end %> 
				</div>
			</div>
		</div>
	</div>
</div>




app/views/stories/search.js.erb
$("#stories-table > tbody").html("");
$("<%= escape_javascript(render partial: 'stories/story', collection: @stories) %>").appendTo("#stories-table");

app/views/stories/view.html.erb
<br><br>
<div class="col-sm-2 col-sm-offset-10 col-md-6 col-md-offset-3">
	<div class="create_test">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-2">
					<h1>Testimony</h1>
						<article>
						  <h4><b>Name:</b> <%= @story.name %></h4>
						  <h4><b>Title:</b> <%= @story.title %></h4>
						  <p><%= @story.content %></p>
						</article>
				</div>
			</div>
		</div>
	</div>
</div>
